'use strict';function z(r,q,m,n){r.M.hc(r.Ta,q,m,n,void 0)}function A(r,q,m){return r.M.Ye(r.Ta,q,m)}function H(r,q,m,n){r.M.ea?z(r,q,m,n):r.M.Jf()._OnMessageFromDOM({type:"event",component:r.Ta,handler:q,dispatchOpts:n||null,data:m,responseId:null})}function J(r,q,m){r.M.B(r.Ta,q,m)}function K(r,q){for(const [m,n]of q)J(r,m,n)}window.cc=class{constructor(r,q){this.M=r;this.Ta=q}cd(){}la(){}};
window.Ze=class{constructor(r,q){this.Id=r;this.kh=q;this.Ia=-1;this.Jb=-Infinity;this.rh=()=>{this.Ia=-1;this.Jb=Date.now();this.Wa=!0;this.Id();this.Wa=!1};this.Jd=this.Wa=!1}};"use strict";function L(r,q){const m=q.elementId,n=r.rb(m,q);r.V.set(m,n);n.style.boxSizing="border-box";q.isVisible||(n.style.display="none");q=r.rc(n);q.addEventListener("focus",()=>{N(r,"elem-focused",m)});q.addEventListener("blur",()=>{N(r,"elem-blurred",m)});r.Bb&&document.body.appendChild(n)}
function O(r,q,m){J(r,q,n=>{const u=r.V.get(n.elementId);return m(u,n)})}function N(r,q,m,n){n||(n={});n.elementId=m;z(r,q,n)}function P(r,q,m,n){n||(n={});n.elementId=m;H(r,q,n)}
window.bc=class extends self.cc{constructor(r,q){super(r,q);this.V=new Map;this.Bb=!0;K(this,[["create",m=>L(this,m)],["destroy",m=>{{m=m.elementId;const n=this.V.get(m);this.Bb&&n.parentElement.removeChild(n);this.V.delete(m)}}],["set-visible",m=>{this.Bb&&(this.V.get(m.elementId).style.display=m.isVisible?"":"none")}],["update-position",m=>{if(this.Bb){var n=this.V.get(m.elementId);n.style.left=m.left+"px";n.style.top=m.top+"px";n.style.width=m.width+"px";n.style.height=m.height+"px";m=m.fontSize;
null!==m&&(n.style.fontSize=m+"em")}}],["update-state",m=>{{const n=this.V.get(m.elementId);this.na(n,m)}}],["focus",m=>{{const n=this.rc(this.V.get(m.elementId));m.focus?n.focus():n.blur()}}],["set-css-style",m=>{this.V.get(m.elementId).style[m.prop]=m.val}],["set-attribute",m=>{this.V.get(m.elementId).setAttribute(m.name,m.val)}],["remove-attribute",m=>{this.V.get(m.elementId).removeAttribute(m.name)}]]);O(this,"get-element",m=>m)}rb(){throw Error("required override");}na(){throw Error("required override");
}rc(r){return r}};"use strict";
{const r=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let q=0;function m(k){const d=document.createElement("script");d.async=!1;d.type="module";return k.wh?new Promise(l=>{const p="c3_resolve_"+q;++q;self[p]=l;d.textContent=k.zh+`\n\nself["${p}"]();`;document.head.appendChild(d)}):new Promise((l,p)=>{d.onload=l;d.onerror=p;d.src=k;document.head.appendChild(d)})}let n=!1,u=!1;function D(){if(!n){try{new Worker("blob://",{get type(){u=!0}})}catch(k){}n=!0}return u}let h=
new Audio;const c={"audio/webm; codecs=opus":!!h.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!h.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!h.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!h.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!h.canPlayType("audio/mp4"),"audio/mpeg":!!h.canPlayType("audio/mpeg")};h=null;async function f(k){k=await a(k);return(new TextDecoder("utf-8")).decode(k)}function a(k){return new Promise((d,
l)=>{const p=new FileReader;p.onload=v=>d(v.target.result);p.onerror=v=>l(v);p.readAsArrayBuffer(k)})}const b=[];let g=0;window.RealFile=window.File;const t=[],w=new Map,y=new Map;let F=0;const E=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");E.push(k)};const I=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.Aa=class k{constructor(d){this.ea=d.Bh;this.bb=null;this.G="";this.Rb=d.yh;this.pb={};this.Nc=this.Xd=null;
this.Fb=[];this.ab=this.P=this.Tc=null;this.Ga=-1;this.ph=()=>this.xg();this.Wd=[];this.s=d.Yd;this.Ib="file"===location.protocol.substr(0,4);!this.ea||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&D()||(this.ea=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ea=!1;if("cordova"===this.s&&this.ea)if(/android/i.test(navigator.userAgent)){const l=/Chrome\/(\d+)/i.exec(navigator.userAgent);l&&90<=parseInt(l[1],10)||(this.ea=!1)}else this.ea=!1;this.Nb=this.fa=null;"html5"!==
this.s&&"playable-ad"!==this.s||!this.Ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.s||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("runtime","cordova-fetch-local-file",l=>this.bg(l));this.B("runtime",
"create-job-worker",()=>this.cg());"cordova"===this.s?document.addEventListener("deviceready",()=>this.ud(d)):this.ud(d)}Le(){return r&&"cordova"===this.s}fc(){const d=navigator.userAgent;return r&&I.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async ud(d){"macos-wkwebview"===this.s&&this.eh();if("playable-ad"===this.s){this.fa=self.c3_base64files;this.Nb={};await this.Cf();for(let p=0,v=d.Ka.length;p<v;++p){var l=d.Ka[p].toLowerCase();this.Nb.hasOwnProperty(l)?d.Ka[p]={wh:!0,
zh:this.Nb[l]}:this.fa.hasOwnProperty(l)&&(d.Ka[p]=URL.createObjectURL(this.fa[l]))}}d.sh?this.G=d.sh:(l=location.origin,this.G=("null"===l?"file:///":l)+location.pathname,l=this.G.lastIndexOf("/"),-1!==l&&(this.G=this.G.substr(0,l+1)));d.Dh&&(this.pb=d.Dh);l=new MessageChannel;this.bb=l.port1;this.bb.onmessage=p=>this._OnMessageFromRuntime(p.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(p=>this.qg(p));this.ab=new self.Me(this);await Q(this.ab);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ea?await this.Pf(d,l.port2):await this.Of(d,l.port2)}tc(d){d=this.pb.hasOwnProperty(d)?this.pb[d]:d.endsWith("/workermain.js")&&this.pb.hasOwnProperty("workermain.js")?this.pb["workermain.js"]:"playable-ad"===this.s&&this.fa.hasOwnProperty(d.toLowerCase())?this.fa[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async ac(d,l,p){if(d.startsWith("blob:"))return new Worker(d,
p);if("cordova"===this.s&&this.Ib)return d=await this.$b(p.vh?d:this.Rb+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),p);d=new URL(d,l);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),p)}return new Worker(d,p)}pa(){return Math.max(window.innerWidth,1)}oa(){return Math.max(window.innerHeight,1)}sd(d){var l=this.ab;return{baseUrl:this.G,windowInnerWidth:this.pa(),
windowInnerHeight:this.oa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.Na(),projectData:d.Ih,previewImageBlobs:window.cr_previewImageBlobs||this.fa,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Gh||"",exportType:d.Yd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Hh,jobScheduler:{inputPort:l.Jc,outputPort:l.Rc,maxNumWorkers:l.mh},supportedAudioFormats:c,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.Rb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Rb+"opus.wasm.wasm",isFileProtocol:this.Ib,isiOSCordova:this.Le(),isiOSWebView:this.fc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Pf(d,l){var p=this.tc(d.Ch);this.Xd=await this.ac(p,this.G,{type:"module",name:"Runtime",vh:!0});this.P=document.createElement("canvas");this.P.style.display="none";p=this.P.transferControlToOffscreen();document.body.appendChild(this.P);window.c3canvas=this.P;let v=d.ad||[],
C=d.Ka;v=await Promise.all(v.map(x=>this.Ba(x)));C=await Promise.all(C.map(x=>this.Ba(x)));if("cordova"===this.s)for(let x=0,B=d.Yb.length;x<B;++x){const G=d.Yb[x],M=G[0];if(M===d.Zc||"scriptsInEvents.js"===M||M.endsWith("/scriptsInEvents.js"))G[1]=await this.Ba(M)}this.Xd.postMessage(Object.assign(this.sd(d),{type:"init-runtime",isInWorker:!0,messagePort:l,canvas:p,workerDependencyScripts:v,engineScripts:C,projectScripts:d.Yb,mainProjectScript:d.Zc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[l,p,...R(this.ab)]);this.Fb=t.map(x=>new x(this));this.rd();self.c3_callFunction=(x,B)=>this.Tc.Qf(x,B);"preview"===this.s&&(self.goToLastErrorScript=()=>this.hc("runtime","go-to-last-error-script"))}async Of(d,l){this.P=document.createElement("canvas");this.P.style.display="none";document.body.appendChild(this.P);window.c3canvas=this.P;this.Fb=t.map(x=>new x(this));this.rd();var p=d.Ka.map(x=>"string"===typeof x?(new URL(x,this.G)).toString():x);Array.isArray(d.ad)&&p.unshift(...d.ad);p=await Promise.all(p.map(x=>
this.Ba(x)));await Promise.all(p.map(x=>m(x)));p=self.C3_ProjectScriptsStatus;const v=d.Zc,C=d.Yb;for(let [x,B]of C)if(B||(B=x),x===v)try{B=await this.Ba(B),await m(B),"preview"!==this.s||p[x]||this.Cd(x,"main script did not run to completion")}catch(G){this.Cd(x,G)}else if("scriptsInEvents.js"===x||x.endsWith("/scriptsInEvents.js"))B=await this.Ba(B),await m(B);"preview"===this.s&&"object"!==typeof self.Eh.Fh?(this.Ab(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.sd(d),{isInWorker:!1,messagePort:l,canvas:this.P,runOnStartupFunctions:E}),this.wd(),this.Nc=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Nc,d))}Cd(d,l){this.Ab();console.error(`[Preview] Failed to load project main script (${d}): `,l);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}wd(){this.Ab()}Ab(){const d=
window.th;d&&(d.parentElement.removeChild(d),window.th=null)}async cg(){const d=await S(this.ab);return{outputPort:d,transferables:[d]}}Jf(){if(this.ea)throw Error("not available in worker mode");return this.Nc}hc(d,l,p,v,C){this.bb.postMessage({type:"event",component:d,handler:l,dispatchOpts:v||null,data:p,responseId:null},C)}Ye(d,l,p){const v=F++,C=new Promise((x,B)=>{y.set(v,{resolve:x,reject:B})});this.bb.postMessage({type:"event",component:d,handler:l,dispatchOpts:null,data:p,responseId:v},void 0);
return C}["_OnMessageFromRuntime"](d){const l=d.type;if("event"===l)return this.hg(d);if("result"===l)this.Bg(d);else if("runtime-ready"===l)this.Cg();else if("alert-error"===l)this.Ab(),alert(d.message);else if("creating-runtime"===l)this.wd();else throw Error(`unknown message '${l}'`);}hg(d){const l=d.component,p=d.handler,v=d.data,C=d.responseId;if(d=w.get(l))if(d=d.get(p)){var x=null;try{x=d(v)}catch(B){console.error(`Exception in '${l}' handler '${p}':`,B);null!==C&&this.zb(C,!1,""+B);return}if(null===
C)return x;x&&x.then?x.then(B=>this.zb(C,!0,B)).catch(B=>{console.error(`Rejection from '${l}' handler '${p}':`,B);this.zb(C,!1,""+B)}):this.zb(C,!0,x)}else console.warn(`[DOM] No handler '${p}' for component '${l}'`);else console.warn(`[DOM] No event handlers for component '${l}'`)}zb(d,l,p){let v;p&&p.transferables&&(v=p.transferables);this.bb.postMessage({type:"result",responseId:d,isOk:l,result:p},v)}Bg(d){const l=d.responseId,p=d.isOk;d=d.result;const v=y.get(l);p?v.resolve(d):v.reject(d);y.delete(l)}B(d,
l,p){let v=w.get(d);v||(v=new Map,w.set(d,v));if(v.has(l))throw Error(`[DOM] Component '${d}' already has handler '${l}'`);v.set(l,p)}static La(d){if(t.includes(d))throw Error("DOM handler already added");t.push(d)}rd(){for(const d of this.Fb)if("runtime"===d.Ta){this.Tc=d;return}throw Error("cannot find runtime DOM handler");}qg(d){this.hc("debugger","message",d)}Cg(){for(const d of this.Fb)d.cd()}static Na(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
e)}static Ed(d){e=!!d}Dd(){-1===this.Ga&&this.Wd.length&&(this.Ga=requestAnimationFrame(this.ph))}Af(){-1!==this.Ga&&(cancelAnimationFrame(this.Ga),this.Ga=-1)}xg(){this.Ga=-1;for(const d of this.Wd)d();this.Dd()}Ac(){this.Tc.Ac()}Ie(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}Je(d){return!this.Ie(d)}async Ba(d){return"cordova"===this.s&&(d.startsWith("file:")||this.Ib&&this.Je(d))?(d.startsWith(this.G)&&(d=d.substr(this.G.length)),d=await this.$b(d),URL.createObjectURL(new Blob([d],
{type:"application/javascript"}))):d}async bg(d){const l=d.filename;switch(d.as){case "text":return await this.oe(l);case "buffer":return await this.$b(l);default:throw Error("unsupported type");}}gd(d){const l=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((p,v)=>{window.resolveLocalFileSystemURL(l,C=>{C.file(p,v)},v)})}async oe(d){d=await this.gd(d);return await f(d)}pc(){if(b.length&&!(8<=g)){g++;var d=b.shift();this.Df(d.filename,d.Ah,d.uh)}}$b(d){return new Promise((l,
p)=>{b.push({filename:d,Ah:v=>{g--;this.pc();l(v)},uh:v=>{g--;this.pc();p(v)}});this.pc()})}async Df(d,l,p){try{const v=await this.gd(d),C=await a(v);l(C)}catch(v){p(v)}}eh(){var d={type:"ready"};if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async Cf(){const d=[];for(const [l,p]of Object.entries(this.fa))d.push(this.Bf(l,
p));await Promise.all(d)}async Bf(d,l){if("object"===typeof l)this.fa[d]=new Blob([l.str],{type:l.type}),this.Nb[d]=l.str;else{let p=await this.Hf(l);p||(p=this.Ef(l));this.fa[d]=p}}async Hf(d){try{return await (await fetch(d)).blob()}catch(l){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",l),null}}Ef(d){d=this.Yg(d);return this.zf(d.data,
d.xh)}Yg(d){var l=d.indexOf(",");if(0>l)throw new URIError("expected comma in data: uri");var p=d.substring(l+1);l=d.substring(5,l).split(";");d=l[0]||"";const v=l[2];p="base64"===l[1]||"base64"===v?atob(p):decodeURIComponent(p);return{xh:d,data:p}}zf(d,l){var p=d.length;let v=p>>2,C=new Uint8Array(p),x=new Uint32Array(C.buffer,0,v),B,G;for(G=B=0;B<v;++B)x[B]=d.charCodeAt(G++)|d.charCodeAt(G++)<<8|d.charCodeAt(G++)<<16|d.charCodeAt(G++)<<24;for(p&=3;p--;)C[G]=d.charCodeAt(G),++G;return new Blob([C],
{type:l})}}}"use strict";
{const r=self.Aa;function q(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const m=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),n={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},u={dispatchUserScriptEvent:!0},D={dispatchRuntimeEvent:!0};function h(e){return new Promise((k,d)=>{const l=document.createElement("link");l.onload=()=>k(l);l.onerror=p=>d(p);l.rel=
"stylesheet";l.href=e;document.head.appendChild(l)})}function c(e){return new Promise((k,d)=>{const l=new Image;l.onload=()=>k(l);l.onerror=p=>d(p);l.src=e})}async function f(e){e=URL.createObjectURL(e);try{return await c(e)}finally{URL.revokeObjectURL(e)}}function a(e){return new Promise((k,d)=>{let l=new FileReader;l.onload=p=>k(p.target.result);l.onerror=p=>d(p);l.readAsText(e)})}async function b(e,k,d){if(!/firefox/i.test(navigator.userAgent))return await f(e);var l=await a(e);l=(new DOMParser).parseFromString(l,
"image/svg+xml");const p=l.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const v=p.getAttribute("width"),C=p.getAttribute("height");if(!v.includes("%")&&!C.includes("%"))return await f(e)}p.setAttribute("width",k+"px");p.setAttribute("height",d+"px");l=(new XMLSerializer).serializeToString(l);e=new Blob([l],{type:"image/svg+xml"});return await f(e)}function g(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const t=new Set(["input",
"textarea","datalist","select"]),w=new Set(["canvas","body","html"]);function y(e){w.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function F(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await f(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const k=e.getBoundingClientRect();document.body.removeChild(e);return[k.width,
k.height]}};self.C3_RasterSvgImageBlob=async function(e,k,d,l,p){e=await b(e,k,d);const v=document.createElement("canvas");v.width=l;v.height=p;v.getContext("2d").drawImage(e,0,0,k,d);return v};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}r.La(class extends self.cc{constructor(e){super(e,"runtime");this.Od=!0;this.Ha=-1;this.Xc="any";this.Fd=this.Gd=!1;this.Ea=
this.ib=this.va=null;this.Pb=this.Ob=0;e.B("canvas","update-size",l=>this.Vg(l));e.B("runtime","invoke-download",l=>this.ng(l));e.B("runtime","raster-svg-image",l=>this.yg(l));e.B("runtime","get-svg-image-size",l=>this.jg(l));e.B("runtime","set-target-orientation",l=>this.Gg(l));e.B("runtime","register-sw",()=>this.zg());e.B("runtime","post-to-debugger",l=>this.Ad(l));e.B("runtime","go-to-script",l=>this.Ad(l));e.B("runtime","before-start-ticking",()=>this.Xf());e.B("runtime","debug-highlight",l=>
this.dg(l));e.B("runtime","enable-device-orientation",()=>this.yf());e.B("runtime","enable-device-motion",()=>this.xf());e.B("runtime","add-stylesheet",l=>this.Uf(l));e.B("runtime","alert",l=>this.Vf(l));e.B("runtime","hide-cordova-splash",()=>this.kg());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const p=l.target;k.has(p.tagName.toLowerCase())||g(p)||l.preventDefault()});const d=e.P;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",
y);d.addEventListener("selectstart",y);d.addEventListener("gesturehold",y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),d.addEventListener("pointerdown",y)):d.addEventListener("touchstart",y);this.cb=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",
()=>this.Wg());window.addEventListener("fullscreenchange",()=>this.Qa());window.addEventListener("webkitfullscreenchange",()=>this.Qa());window.addEventListener("mozfullscreenchange",()=>this.Qa());window.addEventListener("fullscreenerror",l=>this.wc(l));window.addEventListener("webkitfullscreenerror",l=>this.wc(l));window.addEventListener("mozfullscreenerror",l=>this.wc(l));e.fc()&&window.addEventListener("focusout",()=>{{const v=document.activeElement;if(v){var l=v.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));
l="textarea"===l?!0:"input"===l?p.has(v.type.toLowerCase()||"text"):g(v)}else l=!1}l||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=l=>this.Xg(l);this.Oc=new Set;this.nh=new WeakSet;this.lh=!1}Xf(){"cordova"===this.M.s?(document.addEventListener("pause",()=>this.zc(!0)),document.addEventListener("resume",()=>this.zc(!1))):document.addEventListener("visibilitychange",()=>this.zc(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}cd(){window.addEventListener("focus",()=>
this.Sa("window-focus"));window.addEventListener("blur",()=>{this.Sa("window-blur",{parentHasFocus:I()});this.cb=0});window.addEventListener("focusin",k=>{k=k.target;(t.has(k.tagName.toLowerCase())||g(k))&&this.Sa("keyboard-blur")});window.addEventListener("keydown",k=>this.xd("keydown",k));window.addEventListener("keyup",k=>this.xd("keyup",k));window.addEventListener("dblclick",k=>this.xc("dblclick",k,n));window.addEventListener("wheel",k=>this.rg(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
k=>{this.uc(k);this.Ra("pointerdown",k)}),this.M.ea&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ib=new self.Ze(()=>this.Gf(),5),this.ib.Jd=!0,window.addEventListener("pointerrawupdate",k=>this.vg(k))):window.addEventListener("pointermove",k=>this.Ra("pointermove",k)),window.addEventListener("pointerup",k=>this.Ra("pointerup",k)),window.addEventListener("pointercancel",k=>this.Ra("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.uc(k);this.yc("pointerdown",
k)}),window.addEventListener("mousemove",k=>this.yc("pointermove",k)),window.addEventListener("mouseup",k=>this.yc("pointerup",k)),window.addEventListener("touchstart",k=>{this.uc(k);this.yb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.yb("pointermove",k)),window.addEventListener("touchend",k=>this.yb("pointerup",k)),window.addEventListener("touchcancel",k=>this.yb("pointercancel",k)));const e=()=>this.Ac();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Sa(e,k){z(this,e,k||null,D)}pa(){return this.M.pa()}oa(){return this.M.oa()}Wg(){const e=this.pa(),k=this.oa();this.Sa("window-resize",{innerWidth:e,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:r.Na()});this.M.fc()&&(-1!==this.Ha&&clearTimeout(this.Ha),this.Bd(e,k,0))}$g(e,k,d){-1!==this.Ha&&clearTimeout(this.Ha);this.Ha=setTimeout(()=>this.Bd(e,
k,d),48)}Bd(e,k,d){const l=this.pa(),p=this.oa();this.Ha=-1;l!=e||p!=k?this.Sa("window-resize",{innerWidth:l,innerHeight:p,devicePixelRatio:window.devicePixelRatio,isFullscreen:r.Na()}):10>d&&this.$g(l,p,d+1)}Gg(e){this.Xc=e.targetOrientation}ih(){const e=this.Xc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(e):screen.webkitLockOrientation?
k=screen.webkitLockOrientation(e):screen.mozLockOrientation?k=screen.mozLockOrientation(e):screen.msLockOrientation&&(k=screen.msLockOrientation(e));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",k)}}Qa(){const e=r.Na();e&&"any"!==this.Xc&&this.ih();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.pa(),innerHeight:this.oa()})}wc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",
{isFullscreen:r.Na(),innerWidth:this.pa(),innerHeight:this.oa()})}zc(e){e?this.M.Af():this.M.Dd();z(this,"visibilitychange",{hidden:e})}xd(e,k){"Backspace"===k.key&&y(k);const d=m.get(k.code)||k.code;H(this,e,{code:d,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},n)}rg(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},n)}xc(e,k,d){q(k)||H(this,e,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,movementX:k.movementX||0,movementY:k.movementY||0,timeStamp:k.timeStamp},d)}yc(e,k){if(!q(k)){var d=this.cb;"pointerdown"===e&&0!==d?e="pointermove":"pointerup"===e&&0!==k.buttons&&(e="pointermove");H(this,e,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,
movementX:k.movementX||0,movementY:k.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},n);this.cb=k.buttons;this.xc(k.type,k,u)}}Ra(e,k){if(this.ib&&"pointermove"!==e){var d=this.ib;d.Wa||(-1!==d.Ia&&(self.clearTimeout(d.Ia),d.Ia=-1),d.Jb=Date.now())}d=0;"mouse"===k.pointerType&&(d=this.cb);H(this,e,{pointerId:k.pointerId,pointerType:k.pointerType,button:k.button,buttons:k.buttons,lastButtons:d,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,
pageY:k.pageY,movementX:(k.movementX||0)+this.Ob,movementY:(k.movementY||0)+this.Pb,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},n);this.Pb=this.Ob=0;"mouse"===k.pointerType&&(d="mousemove","pointerdown"===e?d="mousedown":"pointerup"===e&&(d="mouseup"),this.xc(d,k,u),this.cb=k.buttons)}vg(e){this.Ea&&(this.Ob+=this.Ea.movementX||0,this.Pb+=this.Ea.movementY||0);this.Ea=
e;e=this.ib;if(-1===e.Ia){var k=Date.now(),d=k-e.Jb,l=e.kh;d>=l&&e.Jd?(e.Jb=k,e.Wa=!0,e.Id(),e.Wa=!1):e.Ia=self.setTimeout(e.rh,Math.max(l-d,4))}}Gf(){this.Ra("pointermove",this.Ea);this.Ea=null}yb(e,k){for(let d=0,l=k.changedTouches.length;d<l;++d){const p=k.changedTouches[d];H(this,e,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,movementX:k.movementX||0,movementY:k.movementY||0,width:2*(p.radiusX||p.webkitRadiusX||
0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:k.timeStamp},n)}}uc(e){window!==window.top&&window.focus();this.vd(e.target)&&document.activeElement&&!this.vd(document.activeElement)&&document.activeElement.blur()}vd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}yf(){this.Gd||(this.Gd=!0,window.addEventListener("deviceorientation",e=>this.fg(e)),window.addEventListener("deviceorientationabsolute",
e=>this.gg(e)))}xf(){this.Fd||(this.Fd=!0,window.addEventListener("devicemotion",e=>this.eg(e)))}fg(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},n)}gg(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},n)}eg(e){let k=null;var d=e.acceleration;d&&(k=
{x:d.x||0,y:d.y||0,z:d.z||0});d=null;var l=e.accelerationIncludingGravity;l&&(d={x:l.x||0,y:l.y||0,z:l.z||0});l=null;const p=e.rotationRate;p&&(l={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});z(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:d,rotationRate:l,interval:e.interval,timeStamp:e.timeStamp},n)}Vg(e){const k=this.M.P;k.style.width=e.styleWidth+"px";k.style.height=e.styleHeight+"px";k.style.marginLeft=e.marginLeft+"px";k.style.marginTop=e.marginTop+"px";this.Od&&(k.style.display=
"",this.Od=!1)}ng(e){const k=e.url;e=e.filename;const d=document.createElement("a"),l=document.body;d.textContent=e;d.href=k;d.download=e;l.appendChild(d);d.click();l.removeChild(d)}async yg(e){var k=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);k=k?await createImageBitmap(e,k):await createImageBitmap(e);return{imageBitmap:k,transferables:[k]}}async jg(e){return await self.C3_GetSvgImageSize(e.blob)}async Uf(e){await h(e.url)}Ac(){var e=
[...this.Oc];this.Oc.clear();if(!this.lh)for(const k of e)(e=k.play())&&e.catch(()=>{this.nh.has(k)||this.Oc.add(k)})}kg(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}dg(e){if(e.show){this.va||(this.va=document.createElement("div"),this.va.id="inspectOutline",document.body.appendChild(this.va));var k=this.va;k.style.display="";k.style.left=e.left-1+"px";k.style.top=e.top-1+"px";k.style.width=e.width+2+"px";k.style.height=e.height+2+"px";k.textContent=e.name}else this.va&&
(this.va.style.display="none")}zg(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}Qf(e,k){return A(this,"js-invoke-function",{name:e,params:k})}Vf(e){alert(e.message)}Xg(e){"entered-fullscreen"===e?(r.Ed(!0),this.Qa()):"exited-fullscreen"===e?(r.Ed(!1),this.Qa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function Q(r){if(r.jh)throw Error("already initialised");r.jh=!0;var q=r.Qb.tc("dispatchworker.js");r.Dc=await r.Qb.ac(q,r.G,{name:"DispatchWorker"});q=new MessageChannel;r.Jc=q.port1;r.Dc.postMessage({type:"_init","in-port":q.port2},[q.port2]);r.Rc=await S(r)}function R(r){return[r.Jc,r.Rc]}
async function S(r){const q=r.Pd.length;var m=r.Qb.tc("jobworker.js");m=await r.Qb.ac(m,r.G,{name:"JobWorker"+q});const n=new MessageChannel,u=new MessageChannel;r.Dc.postMessage({type:"_addJobWorker",port:n.port1},[n.port1]);m.postMessage({type:"init",number:q,"dispatch-port":n.port2,"output-port":u.port2},[n.port2,u.port2]);r.Pd.push(m);return u.port1}
self.Me=class{constructor(r){this.Qb=r;this.G=r.G;this.G="preview"===r.s?this.G+"workers/":this.G+r.Rb;this.mh=Math.min(navigator.hardwareConcurrency||2,16);this.Dc=null;this.Pd=[];this.Rc=this.Jc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Aa({Bh:!0,Ch:"workermain.js",Ka:["scripts/c3runtime.js"],Yb:[],Zc:"",yh:"scripts/",ad:[],Yd:"scirra-arcade"}));"use strict";
{function r(m){m.stopPropagation()}function q(m){13!==m.which&&27!==m.which&&m.stopPropagation()}self.Aa.La(class extends self.bc{constructor(m){super(m,"text-input");O(this,"scroll-to-bottom",n=>this.Dg(n))}rb(m,n){let u;const D=n.type;"textarea"===D?(u=document.createElement("textarea"),u.style.resize="none"):(u=document.createElement("input"),u.type=D);u.style.position="absolute";u.autocomplete="off";u.addEventListener("touchstart",r);u.addEventListener("touchmove",r);u.addEventListener("touchend",
r);u.addEventListener("mousedown",r);u.addEventListener("mouseup",r);u.addEventListener("keydown",q);u.addEventListener("keyup",q);u.addEventListener("click",h=>{h.stopPropagation();P(this,"click",m)});u.addEventListener("dblclick",h=>{h.stopPropagation();P(this,"dblclick",m)});u.addEventListener("input",()=>N(this,"change",m,{text:u.value}));n.id&&(u.id=n.id);this.na(u,n);return u}na(m,n){m.value=n.text;m.placeholder=n.placeholder;m.title=n.title;m.disabled=!n.isEnabled;m.readOnly=n.isReadOnly;m.spellcheck=
n.spellCheck;n=n.maxLength;0>n?m.removeAttribute("maxlength"):m.setAttribute("maxlength",n)}Dg(m){m.scrollTop=m.scrollHeight}})}"use strict";
{function r(q){q.stopPropagation()}self.Aa.La(class extends self.bc{constructor(q){super(q,"button")}rb(q,m){const n=document.createElement("input");var u=n;m.isCheckbox?(n.type="checkbox",u=document.createElement("label"),u.appendChild(n),u.appendChild(document.createTextNode("")),u.style.fontFamily="sans-serif",u.style.userSelect="none",u.style.webkitUserSelect="none",u.style.display="inline-block",u.style.color="black"):n.type="button";u.style.position="absolute";u.addEventListener("touchstart",
r);u.addEventListener("touchmove",r);u.addEventListener("touchend",r);u.addEventListener("mousedown",r);u.addEventListener("mouseup",r);u.addEventListener("keydown",r);u.addEventListener("keyup",r);n.addEventListener("click",()=>P(this,"click",q,{isChecked:n.checked}));m.id&&(n.id=m.id);this.na(u,m);return u}td(q){return"input"===q.tagName.toLowerCase()?q:q.firstChild}rc(q){return this.td(q)}na(q,m){const n=this.td(q);n.checked=m.isChecked;n.disabled=!m.isEnabled;q.title=m.title;q===n?n.value=m.text:
q.lastChild.textContent=m.text}})}"use strict";
{function r(q){q.stopPropagation()}self.Aa.La(class extends self.bc{constructor(q){super(q,"list");O(this,"set-selected-index",(m,n)=>this.Fg(m,n.selectedIndex));O(this,"add-item",(m,n)=>this.Tf(m,n));O(this,"remove-item",(m,n)=>this.Ag(m,n));O(this,"set-item",(m,n)=>this.Eg(m,n));O(this,"clear",m=>this.Zf(m));O(this,"load-state",(m,n)=>this.og(m,n))}rb(q,m){const n=m.isDropdown,u=m.isMultiSelect,D=m.items,h=document.createElement("select");h.style.position="absolute";h.style.userSelect="none";h.style.webkitUserSelect=
"none";h.multiple=u;n||(h.size=2);for(const c of D)h.add(this.qc(c));h.addEventListener("touchstart",r);h.addEventListener("touchmove",r);h.addEventListener("touchend",r);h.addEventListener("mousedown",r);h.addEventListener("mouseup",r);h.addEventListener("click",c=>{c.stopPropagation();P(this,"click",q,this.sc(h))});h.addEventListener("dblclick",c=>{c.stopPropagation();P(this,"dblclick",q,this.sc(h))});h.addEventListener("change",()=>N(this,"change",q,this.sc(h)));m.id&&(h.id=m.id);this.na(h,m);
return h}qc(q){const m=document.createElement("option");m.text=q;return m}sc(q){const m=q.selectedIndex,n=[];for(let u=0,D=q.length;u<D;++u)q.options[u].selected&&n.push(u);return{selectedIndex:m,selectedIndices:n}}na(q,m){q.title=m.title;q.disabled=!m.isEnabled;q.multiple=!!m.isMultiSelect}Fg(q,m){q.selectedIndex=m}Tf(q,m){const n=m.index;m=this.qc(m.text);0>n?q.add(m):q.add(m,n)}Ag(q,m){q.remove(m.index)}Eg(q,m){q.options[m.index].text=m.text}Zf(q){q.innerHTML=""}og(q,m){q.innerHTML="";for(const n of m.items)q.add(this.qc(n));
q.selectedIndex=m.selectedIndex;for(const n of m.selectedIndices)if(m=q.options[n])m.selected=!0}})}"use strict";
{const r=[],q=2*Math.PI;function m(c){c%=q;0>c&&(c+=q);return c}class n{constructor(c,f,a,b,g,t){this.Md=c;this.Xa=f;this.ma=a;this.nb=b;this.Vb=g;this.Kd=t}za(){return{tag:this.nb,interp:this.Xa,userData:this.Vb,cvt:this.Kd}}ja(){return this.Xa}Ge(){return"undefined"!==typeof this.Vb}ed(c){switch(this.ma){case 0:return c;case 1:return Math.fround(c);case 2:return 2===this.Xa&&(c=m(c),c/=Math.PI,c=32767*(c-1)),c|=0,-32768>c?-32768:32767<c?32767:c;case 3:return 2===this.Xa&&(c=m(c),c/=q,c*=255),c|=
0,0>c?0:255<c?255:c;default:return c}}od(c,f,a){switch(this.ma){case 0:c.setFloat64(f,a);f+=8;break;case 1:c.setFloat32(f,a);f+=4;break;case 2:c.setInt16(f,a);f+=2;break;case 3:c.setUint8(f,a);f+=1;break;default:c.setFloat32(f,a),f+=4}return f}wb(c){if(2!==this.Xa)return c;2===this.ma?c=(c/32767+1)*Math.PI:3===this.ma&&(c=c/255*q);return c}static ub(c,f,a,b,g){switch(c){case 0:return g?a:f;case 1:return f+b*(a-f);case 2:return f===a?c=0:(c=Math.sin(f)*Math.sin(a)+Math.cos(f)*Math.cos(a),c=1<=c?0:
-1>=c?Math.PI:Math.acos(c)),f=0>=Math.cos(a)*Math.sin(f)-Math.sin(a)*Math.cos(f)?m(f+c*b):m(f-c*b);default:return g?a:f}}}class u{constructor(c,f){this.timestamp=c;this.data=f}}class D{constructor(c,f,a){this.O=c;this.b=c.b;this.j=f;this.D=a;this.Ua=[];this.Ua.length=this.O.S.length;this.Mc=this.Kb=0;this.Nd=this.Tb=!1;this.H=[];this.o=this.h=this.X=null}za(){var c=[];for(let a=0,b=this.O.S.length;a<b;++a)c.push(this.ja(this.O.Sb,a));c={id:this.j,nid:this.D,isTimedOut:this.Ke(),interpValues:c,latestUpdate:null};
const f=this.xe();f&&(c.latestUpdate={timestamp:f.timestamp,data:f.data});return c}ld(c){this.Nd=!!c}nc(c,f){c=c.netValues;var a=this.O.S;const b=a.length;this.Tb=!1;for(let g=0;g<b;++g){const t=a[g].ed(c[g]);this.Ua[g]!==t&&(this.Ua[g]=t,this.Kb=f,this.O.df(f))}c=f-this.Kb;f-=this.Mc;a=this.O.Hd;(this.Tb=100>c&&0===a?!0:1E3>c&&1>=a?95<=f:495<=f)&&this.O.He()}oc(c,f,a){const b=this.O.S;this.Mc=a;c.setUint16(f,this.D);f+=2;for(let g=0,t=this.Ua.length;g<t;++g)f=b[g].od(c,f,this.Ua[g]);return f}Zb(c,
f){for(let a=0,b=this.H.length;a<b;++a){const g=this.H[a];if(g.timestamp===c)return;if(g.timestamp>c){this.H.splice(a,0,new u(c,f));return}}this.H.push(new u(c,f))}Ke(){return 0===this.H.length?!1:this.H[this.H.length-1].timestamp<this.O.Sb-3E3}la(){for(;2<this.H.length&&this.H[0]!==this.X&&this.H[0]!==this.h&&this.H[0]!==this.o;)this.H.shift();const c=this.O.Sb;if(!(this.o&&this.o.timestamp>c&&this.h&&this.h.timestamp<c)){this.o=null;for(let f=0,a=this.H.length;f<a;++f){const b=this.H[f];if(b.timestamp<=
c){if(!this.h||b.timestamp>this.h.timestamp)this.X=this.h,this.h=b}else{this.o=b;break}}}}xe(){return 0===this.H.length?null:this.H[this.H.length-1]}ja(c,f){if(!this.o&&!this.h)return 0;if(this.o&&!this.h)return this.o.data[f];const a=this.O.S;let b,g,t;if(!this.o&&this.h){if(this.X){var w=this.X.timestamp;b=this.X.data[f];g=this.h.timestamp;t=this.h.data[f];c>this.h.timestamp+this.O.Hb&&(c=this.h.timestamp+this.O.Hb);w=w===g?0:(c-w)/(g-w);return n.ub(a[f].ja(),b,t,w,!0)}return this.h.data[f]}w=this.h.timestamp;
b=this.h.data[f];g=this.o.timestamp;t=this.o.data[f];w=w===g?0:(c-w)/(g-w);return n.ub(a[f].ja(),b,t,w,!1)}}class h{constructor(c,f,a,b){this.b=c;this.lb=f;this.mb=a;this.D=this.b.Be();this.Hd=b;this.Vb={};this.ba=0;this.Hb=250;switch(this.Hd){case 1:this.Hb=500;break;case 2:this.Hb=2500}this.S=[];this.W=[];this.wa=new Map;this.Ja=new Set;this.gb=this.Mc=this.Kb=this.eb=0;this.Da=!1;this.Eb=[];this.fb=new Map;this.Sb=0;this.b.he(this)}ra(c){this.D=c}df(c){this.Kb=c}He(){this.gb++}fh(){this.Da=!0}ia(c,
f,a,b,g){c=new n(this.S.length,c,f,a,b,g);switch(f){case 0:this.ba+=8;break;case 1:this.ba+=4;break;case 2:this.ba+=2;break;case 3:this.ba+=1}this.S.push(c)}Zb(c,f,a){this.ze(f).Zb(c,a)}la(){this.Sb=this.b.tb();for(const c of this.W)c.la()}Ae(){const c=[];for(const f of this.S){const a={tag:f.nb,precision:f.ma,interp:f.ja(),clientvaluetag:f.Kd};f.Ge()&&(a.userdata=f.Vb);c.push(a)}return c}ff(c){this.ba=this.S.length=0;for(const f of c)this.ia(f.interp,f.precision,f.tag,f.userdata,f.clientvaluetag)}ze(c){let f=
this.fb.get(c);if(f)return f;f=new D(this,-1,c);this.fb.set(c,f);this.W.push(f);return f}ye(c){let f=this.wa.get(c);if(f)return f;f=new D(this,c,this.je());this.wa.set(c,f);this.W.push(f);return f}je(){do this.eb++,65535<this.eb&&(this.eb=0);while(this.Ja.has(this.eb));const c=this.eb;this.Ja.add(c);return c}ic(c){const f=c.j,a=c.D;this.b.g()&&!this.Da&&this.Eb.push(a);this.wa.delete(f);this.fb.delete(a);this.Ja.delete(a);c=this.W.indexOf(c);-1<c&&this.W.splice(c,1)}ne(){this.Eb.length=0;this.wa.clear();
this.fb.clear();this.Ja.clear();this.W.length=0}nc(c,f){this.gb=0;for(var a of this.W)a.ld(!1);for(let b=0,g=c.length;b<g;++b){a=c[b];const t=this.ye(a.uid);t.ld(!0);t.nc(a,f)}for(const b of this.W)b.Nd||r.push(b);for(const b of r)this.ic(b);r.length=0}oc(c,f,a){c.setUint16(f,this.D);f+=2;let b=0;this.Da&&(b=1);c.setUint8(f,b);f+=1;c.setUint16(f,this.gb);f+=2;c.setUint16(f,this.ba);f+=2;for(const g of this.W)g.Tb&&(f=g.oc(c,f,a));return f}Xe(c,f){if(this.wa.has(c))console.warn("OverrideNid passed id "+
c+" which is already in use and cannot be overridden");else if(this.Ja.has(f))console.warn("OverrideNid passed nid "+f+" which is already in use and cannot be overridden");else{var a=new D(this,c,f);this.wa.set(c,a);this.Ja.add(f);this.W.push(a);this.Da=!0}}jc(c){(c=this.wa.get(c))&&this.ic(c)}kc(c){(c=this.fb.get(c))&&this.ic(c)}za(){return{hasOverriddenNids:this.Da,netValues:this.S.map(c=>c.za()),netInstances:this.W.map(c=>c.za())}}De(){return{roId:this.lb,sid:this.mb,netValues:this.S.map(c=>c.za())}}}
self.dd=n;self.ke=u;self.me=h}"use strict";
{const r=self.ke,q=self.dd,m=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function n(h){if(h)try{h.close()}catch(c){}}const u=[];class D{constructor(h,c,f){this.b=h;this.j=c;this.D=0;this.J=f;this.sa=this.l=null;this.Ya=!1;this.ta=null;this.Za=!1;this.ua=null;this.Gc=this.ob=this.Va=this.Ca=this.$a=!1;this.Gb=this.Ld=this.Kc=0;this.Ud=[];this.Sd=this.Rd=0;this.R=[];this.o=this.h=this.X=null;this.Qd=0;this.Bc=!1;this.Lc=1;this.Lb=
[];this.Vd=this.Mb=0;this.b.wf(this)}ra(h){this.D=h}g(){return this===this.b.A}vb(){return this===this.b.v}gh(){this.Rd=performance.now()}hh(h){this.Sd=h}xb(h,c){h.binaryType="arraybuffer";h.onopen=()=>{"o"===c?this.Ya=!0:"r"===c?this.Za=!0:"u"===c&&(this.$a=!0);this.Sf()};h.onmessage=f=>{this.pg(c,f)};h.onerror=f=>{console.error("Peer '"+this.j+"' datachannel '"+c+"' error: ",f);this.b.Z(this,f);this.b.g()&&!this.g()&&this.C("network error")};h.onclose=()=>{this.C("disconnect")}}fd(){if(!this.vb()){var h=
this.b.g();this.Va=this.Ca=this.$a=this.Za=this.Ya=!1;this.Ld=performance.now();this.l=new m({iceServers:this.b.Ic});this.l.onicecandidate=f=>{f.candidate&&this.b.Y({message:"icecandidate",toclientid:this.j,icecandidate:f.candidate})};this.l.onsignalingstatechange=()=>{this.l&&"closed"===this.l.signalingState&&this.C("disconnect")};this.l.oniceconnectionstatechange=()=>{this.l&&("failed"!==this.l.iceConnectionState&&"closed"!==this.l.iceConnectionState||this.C("disconnect"))};this.l.onconnectionstatechange=
()=>{if(this.l){var f=this.l.connectionState;"failed"!==f&&"closed"!==f||this.C("disconnect")}};var c=`c2mp_${this.b.se()}_${this.b.te()}_${this.b.ue()}`;h?(this.D=this.b.bd(),this.sa=this.l.createDataChannel("o",{ordered:!0,protocol:c}),this.xb(this.sa,"o"),this.ta=this.l.createDataChannel("r",{ordered:!1,protocol:c}),this.xb(this.ta,"r"),this.ua=this.l.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:c}),this.xb(this.ua,"u"),this.l.createOffer().then(f=>{this.l.setLocalDescription(f);
this.b.Y({message:"offer",toclientid:this.j,offer:f})}).catch(f=>{console.error("Host error creating offer for peer '"+this.j+"': ",f);this.b.Z(this,"could not create offer for peer")})):this.l.ondatachannel=f=>{if(f.channel.protocol!==c)console.error("Unexpected datachannel protocol '"+f.channel.protocol+"', should be '"+c+"'"),this.b.Z(this,"unexpected datachannel protocol '"+f.channel.protocol+"', should be '"+c+"'");else{var a=f.channel.label;"o"===a?this.sa=f.channel:"r"===a?this.ta=f.channel:
"u"===a?this.ua=f.channel:(console.error("Unknown datachannel label: "+f.channel.label),this.b.Z(this,"unknown datachannel label '"+f.channel.label+"'"));this.xb(f.channel,a)}}}}async vf(h){if(this.l)try{await this.l.addIceCandidate(h)}catch(c){console.warn("[Multiplayer] Error adding ICE candidate: ",c)}}Fe(){return!!this.l}Sf(){!this.Ca&&this.Za&&this.$a&&this.Ya&&(this.sg(),this.Ca=!0,this.Va=!1)}sg(){this.Kc=performance.now();if(this.b.g()){this.b.Ma("o",JSON.stringify({c:"j",i:this.j,n:this.D,
a:this.J}),this);this.ka("o",JSON.stringify({c:"hi",hn:this.b.A.D,n:this.D,d:this.b.U,u:this.b.hb,objs:this.b.Ce(),cvs:this.b.re()}));for(const h of this.b.aa)!h.g()&&h!==this&&h.ec()&&this.ka("o",JSON.stringify({c:"j",i:h.j,n:h.D,a:h.J}))}else this.Gc=!0,this.g()&&this.lc(performance.now(),!0);this.b.zd(this)}Rf(h){!this.Va&&this.Ca&&(this.$f(h),this.Va=!0,this.Ca=!1)}$f(h){this.b.g()&&!this.vb()&&this.b.Ma("o",JSON.stringify({c:"l",i:this.j,a:this.J,r:h}),this);this.vb()||this.b.yd(this,h)}ec(){return this.Ca&&
!this.Va}ka(h,c){this.b.tf();var f=0;c.length?f=c.length:c.byteLength&&(f=c.byteLength);this.b.rf(f);f=this.b.Vc;const a=this.b.Uc,b=this.b.Wc;if(!(0<f&&"u"===h&&Math.random()<f))if(0===a&&0===b)this.qd(h,c);else{let g=1;"u"!==h&&Math.random()<f&&(g=3);setTimeout(()=>this.qd(h,c),a*g+Math.random()*b*g)}}qd(h,c){try{"o"===h?this.Ya&&this.sa&&this.sa.send(c):"r"===h?this.Za&&this.ta&&this.ta.send(c):"u"===h&&this.$a&&this.ua&&this.ua.send(c)}catch(f){this.ob||(this.b.g()?"o"===h||"r"===h?("string"===
typeof c?(console.error("Error sending "+c.length+"-char string on '"+h+"' to '"+this.J+"', host kicking: ",f),console.log("String that failed to send from previous error was: "+c)):console.error("Error sending "+(c.length||c.byteLength)+"-byte binary on '"+h+"' to '"+this.J+"', host kicking: ",f),this.C("network error")):(this.Gb++,10<=this.Gb&&("string"===typeof c?(console.error("Too many errors ("+this.Gb+") sending data on '"+h+"' to '"+this.J+"', kicking; last error was for sending "+c.length+
"-char string: ",f),console.log("String that failed to send from previous error was: "+c)):console.error("Too many errors ("+this.Gb+") sending data on '"+h+"' to '"+this.J+"', kicking; last error was for sending "+(c.length||c.byteLength)+"-byte binary: ",f),this.C("network error"))):console.error("Error sending data on '"+h+"': ",f))}}lc(h,c){this.ob||(!c&&!this.ec()&&this.l&&25E3<h-this.Ld?(console.warn("Timed out '"+this.J+"', could not establish connection after 25sec"),this.C("timeout")):!c&&
this.ec()&&2E4<h-this.Kc?(console.warn("Timed out '"+this.J+"', not heard from for 20sec"),this.C("timeout")):(this.Qd=h,this.Bc=!0,this.Lc++,this.ka("u","ping:"+this.Lc)))}$e(h){h="pong:"+h.substr(5);this.b.g()&&(h=h+"/"+Math.round(performance.now()).toString());this.ka("u",h)}wg(h){if(this.Bc){var c=h.indexOf(":");if(-1<c){if(parseFloat(h.substr(c+1))===this.Lc){c=performance.now();this.Bc=!1;var f=(c-this.Qd)/2;this.Lb.push(f);10<this.Lb.length&&this.Lb.shift();u.push(...this.Lb);u.sort((t,w)=>
t-w);this.Vd=u[u.length-1]-u[0];var a=0,b=u.length;4<=u.length&&6>=u.length?(++a,--b):6<u.length&&(a+=2,b-=2);var g=0;for(let t=a;t<b;++t)g+=u[t];this.Mb=g/(b-a);u.length=0;this.b.g()||(a=h.indexOf("/"),-1<a?(h=parseFloat(h.substr(a+1)),isFinite(h)?this.b.ge(h,c,f,this.Mb):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}pg(h,c){const f=this.b.Vc,a=this.b.Uc,b=this.b.Wc;if(!(0<
f&&"u"===h&&Math.random()<f))if(0===a&&0===b)this.pd(h,c);else{let g=1;"u"!==h&&Math.random()<f&&(g=3);setTimeout(()=>this.pd(h,c),a*g+Math.random()*b*g)}}pd(h,c){if(!this.ob){this.Kc=performance.now();this.b.sf();var f=0;c.data.length?f=c.data.length:c.data.byteLength&&(f=c.data.byteLength);this.b.qf(f);if("string"===typeof c.data){if(!(""===c.data.trim()||4>c.data.length))if(h=c.data.substr(0,4),"ping"===h)this.$e(c.data);else if("pong"===h)this.wg(c.data);else{try{var a=JSON.parse(c.data)}catch(b){this.b.Z(this,
b);this.b.g()?(console.error("Error parsing message as JSON for peer '"+this.j+"', host kicking: ",b),this.C("data error")):console.error("Error parsing message as JSON for peer '"+this.j+"': ",b);console.log("String that failed to parse from previous error: "+c.data);return}if(a)try{a.c&&"m"!==a.c?this.ag(a):this.b.tg(this,a)}catch(b){this.b.Z(this,b),this.b.g()?(console.error("Error handling message for peer '"+this.j+"', host kicking: ",b),this.C("data error")):console.error("Error handling message for peer '"+
this.j+"': ",b)}}}else{!this.Gc&&this.b.g()&&"u"===h&&(this.Gc=!0,this.b.jf(this.j));try{this.Yf(c.data)}catch(b){this.b.Z(this,b),this.b.g()?(console.error("Error handling binary update for peer '"+this.j+"', host kicking: ",b),this.C("data error")):console.error("Error handling binary update for peer '"+this.j+"': ",b)}}}}ag(h){switch(h.c){case "disconnect":h.k&&z(this.b,"peer-kicked");var c=!this.b.g()&&!this.g();this.C(h.r);c&&this.b.mc();break;case "hi":this.b.g()||(this.b.A.ra(h.hn),this.b.v.ra(h.n),
this.b.cf(h.d),this.b.gf(h.u),this.b.Oe(h.objs),this.b.Ne(h.cvs));break;case "j":this.b.g()||(c=new D(this.b,h.i,h.a),c.ra(h.n),this.b.zd(c));break;case "l":!this.b.g()&&(c=this.b.sb(h.i))&&(c.vb()||this.b.yd(c,h.r),c.C(h.r));break;default:console.error("Unknown control message from peer '"+this.j+"': "+h.c),this.b.Z(this,"unknown control message '"+h.c+"'")}}Yf(h){this.b.g()?this.lg(h):this.ug(h)}lg(h){h=new DataView(h);let c=0;var f=h.getUint32(c);c+=4;if(1664249200!==f)console.warn("Rejected packet with incorrect magic number (received '"+
f+"', expected '1664249200'");else if(f=h.getFloat64(c),c+=8,f+=this.Mb,!(3E3<=Math.abs(f-performance.now()))){h.getUint8(c);c+=1;var a=h.getUint8(c);c+=1;var b=[],g=this.b.$;for(let w=0;w<a;++w)if(w>=g.length)b.push(0);else{var t=g[w];switch(t.ma){case 0:t=h.getFloat64(c);c+=8;break;case 1:t=h.getFloat32(c);c+=4;break;case 2:t=t.wb(h.getInt16(c));c+=2;break;case 3:t=t.wb(h.getUint8(c));c+=1;break;default:t=h.getFloat32(c),c+=4}b.push(t)}this.uf(f,b)}}uf(h,c){for(let f=0,a=this.R.length;f<a;++f){const b=
this.R[f];if(b.timestamp===h)return;if(b.timestamp>h){this.R.splice(f,0,new r(h,c));return}}this.R.push(new r(h,c))}la(h){if(0!==this.R.length){for(;2<this.R.length&&this.R[0]!==this.X&&this.R[0]!==this.h&&this.R[0]!==this.o;)this.R.shift();if(!(this.o&&this.o.timestamp>h&&this.h&&this.h.timestamp<h)){this.o=null;for(let c=0,f=this.R.length;c<f;++c){const a=this.R[c];if(a.timestamp<=h){if(!this.h||a.timestamp>this.h.timestamp)this.X=this.h,this.h=a}else{this.o=a;break}}}}}ug(h){h=new DataView(h);
let c=0;var f=h.getUint32(c);c+=4;1664249200!==f?console.warn("Rejected packet with incorrect magic number (received '"+f+"', expected '1664249200'"):(f=h.getUint32(c),c+=4,0===f?this.Nf(h,c):1===f?this.Mf(h,c):console.warn("Ignoring packet with incorrect flags (received "+f+", expected 0 or 1"))}Nf(h,c){const f=h.getFloat64(c);c+=8;const a=h.getUint16(c);c+=2;for(let w=0;w<a;++w){var b=h.getUint16(c);c+=2;var g=h.getUint8(c);c+=1;let y=null,F=0;const E=this.b.jd(b);E?(y=E.S,F=y.length,1===g&&E.fh()):
console.warn("Don't know which object corresponds to NID "+b);b=h.getUint16(c);c+=2;g=h.getUint16(c);c+=2;for(let I=0;I<b;++I){const e=h.getUint16(c);c+=2;if(E){const k=[];let d=c;for(let l=0;l<F;++l){var t=y[l];switch(t.ma){case 0:t=h.getFloat64(d);d+=8;break;case 1:t=h.getFloat32(d);d+=4;break;case 2:t=t.wb(h.getInt16(d));d+=2;break;case 3:t=t.wb(h.getUint8(d));d+=1;break;default:t=h.getFloat32(d),d+=4}k.push(t)}E.Zb(f,e,k)}c+=g}}}Mf(h,c){const f=h.getFloat64(c);c+=8;const a=h.getUint16(c);c+=2;
for(let g=0;g<a;++g){var b=h.getUint16(c);c+=2;const t=this.b.jd(b);t||console.warn("Don't know which object corresponds to NID "+b);b=h.getUint16(c);c+=2;for(let w=0;w<b;++w){const y=h.getUint16(c);c+=2;t&&!t.Da&&(this.b.mg(t,y,f),t.kc(y))}}}C(h,c){if(!this.ob){this.ob=!0;this.Rf(h);this.ka("o",JSON.stringify({c:"disconnect",r:h,k:!!c}));var f=this.sa,a=this.ta,b=this.ua,g=this.l;setTimeout(()=>{n(f);n(a);n(b);n(g)},0);this.l=this.ua=this.ta=this.sa=null;this.$a=this.Za=this.Ya=!1;this.b.Zg(this)}}we(h){h=
h.Md;if(!this.o&&!this.h)return 0;if(this.o&&!this.h){var c=this.o.data;return 0>h||h>=c.length?0:c[h]}var f=this.b.tb();let a,b;if(!this.o&&this.h){if(this.X){var g=this.X.timestamp;c=this.X.data[h];a=this.h.timestamp;b=this.h.data[h];f>this.h.timestamp+250&&(f=this.h.timestamp+250);g=g===a?0:(f-g)/(a-g);return q.ub(this.b.$[h].ja(),c,b,g,!0)}c=this.h.data;return 0>h||h>=c.length?0:c[h]}g=this.h.timestamp;c=this.h.data[h];a=this.o.timestamp;b=this.o.data[h];g=g===a?0:(f-g)/(a-g);return q.ub(this.b.$[h].ja(),
c,b,g,!1)}}self.le=D}"use strict";
{const r=self.dd,q=self.le,m=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,n=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,u=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,D=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,h=[{urls:"stun:stun.l.google.com:19302"}];
let c=!1;const f=[];self.Aa.La(class extends self.cc{constructor(a){super(a,"multiplayer");this.Ic=[];this.F=null;this.N=this.ca=!1;this.qh={ee:0,version:0,name:"",be:"",ae:""};this.K=this.Fc=this.Ec=this.Pc=this.Qc="";this.aa=[];this.ga=new Map;this.Fa=0;this.Ub=new Set;this.A=this.v=null;this.U=80;this.hb=this.Hc=30;this.Td=0;this.ya={qb:0,de:0,$c:0,ce:0,Xb:0,$d:0,Yc:0,Zd:0,Wb:0};this.Db=new ArrayBuffer(262144);this.Cc=new DataView(this.Db);this.T=[];this.oh=1;this.jb=new Map;this.kb=new Map;this.Vc=
this.Wc=this.Uc=0;this.xa=[];this.I=this.da=0;this.L=this.ha=this.U;this.$=[];this.Cb=new Map;this.Sc=!1;this.vc(h);setInterval(()=>this.Ff(),2E3);window.addEventListener("unload",()=>this.Pa("quit"));J(this,"get-supported",()=>this.ig());J(this,"add-ice-servers",b=>this.vc(b.list));J(this,"simulate-latency",b=>this.ef(b.latency,b.pdv,b.loss));J(this,"set-bandwidth-profile",b=>this.bf(b.updateRate,b.delay));J(this,"tick",b=>this.la(b));J(this,"alert",b=>this.ie(b));J(this,"signalling-connect",b=>
this.kf(b.url));J(this,"signalling-disconnect",()=>this.nd());J(this,"signalling-login",b=>this.mf(b.alias));J(this,"signalling-join-room",b=>this.lf(b.game,b.instance,b.room,b.maxClients));J(this,"signalling-auto-join-room",b=>this.hf(b.game,b.instance,b.room,b.maxClients,b.lock));J(this,"signalling-leave-room",()=>this.mc());J(this,"signalling-list-game-instances",b=>this.nf(b.game));J(this,"signalling-list-rooms",b=>this.pf(b.game,b.instance,b.which));J(this,"disconnect-room",()=>this.hd(!0));
J(this,"peer-send-message",b=>this.Se(b));J(this,"host-broadcast",b=>this.Qe(b));J(this,"kick-peer",b=>this.Re(b));J(this,"sync-object",b=>this.We(b));J(this,"sync-inst-var",b=>this.Ve(b));J(this,"associate-object",b=>this.Pe(b));J(this,"remove-object-id",b=>this.jc(b.uid));J(this,"remove-net-insts",b=>this.Te(b));J(this,"remove-object-nid",b=>this.Ue(b));J(this,"set-client-state",b=>this.md(b.tag,b.value));J(this,"add-client-input-value",b=>this.fe(b.tag,b.precision,b.interp))}If(a){return a?"string"===
typeof a?a:"string"===typeof a.message?a.message:"string"===typeof a.details?a.details:"string"===typeof a.data?a.data:"string"===typeof a.type?a.type:"unknown error":"unknown error"}dc(){return this.ca&&this.N}Oa(){return this.dc()&&this.K}g(){return this.Oa()&&this.v&&this.A===this.v}se(){return this.dc()?this.Ec:""}te(){return this.dc()?this.Fc:""}ue(){return this.Oa()?this.K:""}ef(a,b,g){this.Uc=Math.max(a,0);this.Wc=Math.max(b,0);this.Vc=Math.max(g,0)}ig(){return{isSupported:!(!m||!D)}}kf(a){if(!this.F&&
!this.ca){try{this.F=new WebSocket(a,"c2multiplayer")}catch(b){this.F=null;this.qa(b);return}this.F.onopen=()=>{-1===this.F.protocol.indexOf("c2multiplayer")?(this.qa("server does not support 'c2multiplayer' protocol"),this.F.close(1002,"'c2multiplayer' protocol required"),this.F=null,this.ca=!1):this.ca=!0};this.F.onclose=()=>{this.Hg();this.N=this.ca=!1;this.F=null};this.F.onerror=b=>{console.error("Signalling server error: ",b);this.qa(b)};this.F.onmessage=b=>{this.Ig(b)}}}nd(){this.F&&this.ca&&
(this.F.close(),this.F=null,this.ca=!1)}Ig(a){let b;try{b=JSON.parse(a.data)}catch(g){this.qa(g);return}switch(b.message){case "welcome":this.Ug(b);break;case "login-ok":this.Pg(b);break;case "join-ok":this.Mg(b);break;case "leave-ok":this.Og();break;case "kicked":this.Ng();break;case "peer-joined":this.Rg(b);break;case "peer-quit":this.Sg(b);break;case "icecandidate":this.Kg(b);break;case "offer":this.Qg(b);break;case "answer":this.Jg(b);break;case "instance-list":this.Lg(b);break;case "room-list":this.Tg(b);
break;case "error":this.qa(b.details);break;default:this.qa("received unknown signalling message")}}Ee(a){for(const b of this.Ic)if(b.urls===a.urls)return!0;return!1}vc(a){if(a)for(let b of a)"string"===typeof b&&(b={urls:b}),this.Ee(b)||(b.hasOwnProperty("url")||(b.url=b.urls),this.Ic.push(b))}qa(a){z(this,"signalling-error",{message:this.If(a)})}Hg(){z(this,"signalling-close")}Ug(a){if(1>a.protocolrev||1<a.protocolrev)this.qa("signalling server protocol revision not supported"),this.nd();else{this.Qc=
a.clientid;var b=this.qh;b.ee=a.protocolrev;b.version=a.version;b.name=a.name;b.be=a.operator;b.ae=a.motd;this.vc(a.ice_servers);z(this,"signalling-welcome",{myid:this.Qc,sigservinfo:{protocolrev:b.ee,version:b.version,name:b.name,operator:b.be,motd:b.ae}})}}Pg(a){this.Pc=a.alias;this.N=!0;z(this,"signalling-login-ok",{myalias:this.Pc})}Be(){return this.oh++}bd(){if(this.g()){do this.Fa++,65535<this.Fa&&(this.Fa=0);while(this.Ub.has(this.Fa));var a=this.Fa;this.Ub.add(a);return a}}pe(a){this.g()&&
this.Ub.delete(a)}Mg(a){this.Pa("disconnect");this.Ec=a.game;this.Fc=a.instance;this.K=a.room;this.v=new q(this,this.Qc,this.Pc);a.host?(this.A=this.v,this.Fa=0,this.Ub.clear(),this.A.ra(this.bd())):(this.I=this.da=this.xa.length=0,this.U=80,this.hb=this.Hc=30,this.L=this.ha=this.U,this.A=new q(this,a.hostid,a.hostalias),this.A.fd());z(this,"signalling-join-ok",{isHost:!!a.host,hostId:this.A.j,hostAlias:this.A.J,game:this.Ec,gameInstance:this.Fc,room:this.K})}Og(){this.K="";z(this,"signalling-leave-ok")}Ng(){this.hd();
this.K="";z(this,"signalling-kicked")}Rg(a){if(this.N&&this.K&&this.g()){var b=this.ga.get(a.peerid);b&&b.C("rejoin");(new q(this,a.peerid,a.peeralias)).fd()}}Sg(a){if(this.N&&this.K&&this.g()){var b=this.ga.get(a.id);b&&b.C(a.reason)}}Kg(a){if(this.N&&this.K){var b=this.ga.get(a.from);b&&b.vf(new u(a.icecandidate))}}Qg(a){if(this.N&&this.K&&!this.g()&&this.v&&this.A&&this.A.Fe()&&a.from===this.A.j){var b=this.A.l;b.setRemoteDescription(new n(a.offer)).then(()=>{b.createAnswer().then(g=>{b.setLocalDescription(g);
this.Y({message:"answer",toclientid:this.A.j,answer:g})}).catch(g=>{console.error("Peer error creating answer: ",g);this.Z(this.v,"could not create answer to host offer")})}).catch(g=>{console.error("Peer error setting remote description: ",g);this.Z(this.v,"could not set remote description")})}}Jg(a){if(this.N&&this.K&&this.g()){var b=this.ga.get(a.from);b&&b.l.setRemoteDescription(new n(a.answer)).catch(g=>{console.error("Host error setting remote description: ",g)})}}Lg(a){z(this,"signalling-instance-list",
{list:a.list})}Tg(a){z(this,"signalling-room-list",{list:a.list})}Y(a){this.F&&this.ca&&this.F.send(JSON.stringify(a))}mf(a){this.N||this.Y({message:"login",protocolrev:1,alias:a})}lf(a,b,g,t){this.N&&!this.K&&this.Y({message:"join",game:a,instance:b,room:g,max_clients:t})}hf(a,b,g,t,w){this.N&&!this.K&&this.Y({message:"auto-join",game:a,instance:b,room:g,max_clients:t,lock_when_full:w})}mc(){this.N&&this.Y({message:"leave"})}jf(a){this.N&&this.g()&&this.Y({message:"confirm-peer",id:a})}nf(a){this.F&&
this.ca&&this.Y({message:"list-instances",game:a})}pf(a,b,g){this.F&&this.ca&&this.Y({message:"list-rooms",game:a,instance:b,which:g})}hd(a){this.I=this.da=this.xa.length=0;this.Pa("disconnect");for(const b of this.T)b.ne();a&&this.mc()}wf(a){this.aa.push(a);this.ga.set(a.j,a);z(this,"add-peer",{id:a.j,alias:a.J})}Zg(a){z(this,"remove-peer",{id:a.j});this.g()&&this.pe(a.D);const b=this.aa.indexOf(a);-1<b&&this.aa.splice(b,1);this.ga.delete(a.j);this.A===a&&(this.A=null,this.Pa("host quit"));this.v===
a&&(this.v=null,this.K="",this.Pa("disconnect"))}Pa(a){if(!c){for(c=!0;this.aa.length;)this.aa[0].C(a);c=!1}}sb(a){return this.ga.get(a)||null}qe(a){return(a=this.ga.get(a))?a.J:""}Qe(a){const b=a.fromId,g=a.tag,t=a.message;a=a.mode;const w=this.sb(b);this.Ma(a,JSON.stringify({c:"m",t:g,f:b,m:t}),w)}Ma(a,b,g){if(this.g()){var t=this.aa.slice(0);for(const w of t)w&&w!==this.v&&w!==g&&w.ka(a,b)}}Ff(){const a=performance.now();if(this.g()){f.push(...this.aa);for(const b of f)b&&b!==this.v&&b.lc(a,!1);
f.length=0}else this.A&&this.A.lc(a,!1)}he(a){this.T.push(a);this.kb.set(a.lb,a);this.jb.set(a.D,a)}Ce(){const a={};for(const [b,g]of this.jb.entries())a[g.mb]={nid:b,nvs:g.Ae()};return a}Oe(a){this.jb.clear();for(const b of this.T)if(a.hasOwnProperty(b.mb.toString())){const g=a[b.mb.toString()];b.ra(g.nid);this.jb.set(g.nid,b);b.ff(g.nvs)}else console.warn("Could not map object SID '"+b.mb+"' - host did not send NID for it"),b.ra(-1)}jd(a){return this.jb.get(a)||null}la(a){if(!this.Oa())return null;
a=a.dt;const b=performance.now();b-this.Td>=1E3/(this.g()?this.Hc:this.hb)-5&&(this.af(b),this.Td=b);const g=this.ya;1E3<=b-g.qb&&(g.de=g.$c,g.ce=g.Xb,g.$d=g.Yc,g.Zd=g.Wb,g.$c=0,g.Xb=0,g.Yc=0,g.Wb=0,g.qb+=1E3,500<b-g.qb&&(g.qb=b),z(this,"stats",{stats:{outboundPerSec:g.de,outboundBandwidthPerSec:g.ce,inboundPerSec:g.$d,inboundBandwidthPerSec:g.Zd}}));this.g()||(this.I<this.da?(this.I+=10*a,this.I>this.da&&(this.I=this.da)):this.I>this.da&&(this.I-=10*a,this.I<this.da&&(this.I=this.da)),this.L<this.ha?
(this.L+=30*a,this.L>this.ha&&(this.L=this.ha)):this.L>this.ha&&(this.L-=30*a,this.L<this.ha&&(this.L=this.ha)));a=this.tb();for(const t of this.aa)t.la(a);for(const t of this.T)t.la();return{simulationTime:this.tb(),hostInputArrivalTime:this.ve(),clientDelay:this.U,peerData:this.Kf(),roData:this.Lf(),isReadyForInput:this.kd()}}Kf(){const a={};for(const b of this.aa){const g={};for(const t of this.$)g[t.nb]=b.we(t);a[b.j]={nid:b.D,latency:b.Mb,pdv:b.Vd,clientState:g}}return a}Lf(){const a={};for(const b of this.T)a[b.lb]=
b.za();return a}async af(a){this.g()?(await this.dh(a),this.bh(a)):await this.ah(a)}async Wf(){const a=await A(this,"before-client-update");for(const b of a.clientStateUpdates)this.md(b.tag,b.value)}async ah(a){this.kd()&&await this.Wf();if(this.v&&this.Sc){var b=this.Cc,g=0,t=this.$,w=this.v.Ud,y=a-this.v.Rd,F=a-this.v.Sd;if(100>y||(1E3>y?95<=F:495<=F)){b.setUint32(g,1664249200);g+=4;b.setFloat64(g,a+this.I);g+=8;b.setUint8(g,0);g+=1;b.setUint8(g,t.length);g+=1;for(let E=0,I=t.length;E<I;++E)y=t[E],
F=0,E<w.length&&(F=y.ed(w[E])),g=y.od(b,g,F);this.v.hh(a);this.A.ka("u",new Uint8Array(this.Db.slice(0,g)))}}}async dh(a){const b=this.Cc;let g=0,t=0;const w=await A(this,"get-object-info",{ros:this.T.map(y=>y.De())});for(const y of this.T){const F=y.lb;w.hasOwnProperty(F)&&(y.nc(w[F],a),0<y.gb&&t++)}if(0!==t){b.setUint32(g,1664249200);g+=4;b.setUint32(g,0);g+=4;b.setFloat64(g,a);g+=8;b.setUint16(g,t);g+=2;for(const y of this.T)0<y.gb&&(g=y.oc(b,g,a));this.Ma("u",new Uint8Array(this.Db.slice(0,g)),
null)}}bh(a){const b=this.Cc;let g=0,t=0;for(const w of this.T)w.Eb.length&&t++;if(0!==t){b.setUint32(g,1664249200);g+=4;b.setUint32(g,1);g+=4;b.setFloat64(g,a);g+=8;b.setUint16(g,t);g+=2;for(const w of this.T)if(a=w.Eb,a.length){b.setUint16(g,w.D);g+=2;b.setUint16(g,a.length);g+=2;for(const y of a)b.setUint16(g,y),g+=2;a.length=0}this.Ma("r",new Uint8Array(this.Db.slice(0,g)),null)}}ge(a,b,g,t){if(!this.g()){this.ha=t+this.U;a=a+g-b;0===this.xa.length&&(this.I=a,this.L=this.ha);this.xa.push(a);30<
this.xa.length&&this.xa.shift();f.push(...this.xa);f.sort((w,y)=>w-y);a=0;b=f.length;4<=f.length&&6>=f.length?(++a,--b):6<f.length&&19>=f.length?(a+=2,b-=2):19<f.length&&(a+=5,b-=5);g=0;for(t=a;t<b;++t)g+=f[t];this.da=g/(b-a);f.length=0}}tb(){return this.g()?performance.now()-this.U:performance.now()+this.I-this.L}ve(){return this.g()?performance.now():performance.now()+this.I+this.L}md(a,b){if(!this.g()&&this.v&&this.Sc&&(a=this.Cb.get(a))){a=a.Md;var g=this.v.Ud;g.length<a+1&&(g.length=a+1);g[a]!==
b&&(g[a]=b,this.v.gh())}}fe(a,b,g){b=new r(this.$.length,g,b,a,null);this.Cb.set(a,b);this.$.push(b)}re(){const a=[];for(const b of this.$)a.push({tag:b.nb,precision:b.ma,interp:b.ja()});return a}Ne(a){this.Cb.clear();this.$.length=0;for(let g=0,t=a.length;g<t;++g){var b=a[g];b=new r(g,b.interp,b.precision,b.tag,null);this.Cb.set(b.nb,b);this.$.push(b)}this.Sc=!0}jc(a){for(const b of this.T)b.jc(a)}kd(){return this.Oa()?this.g()?!0:0!==this.da:!1}bf(a,b){this.Oa()||(this.hb=this.Hc=a,this.U=b)}zd(a){z(this,
"peer-open",{id:a.j,alias:a.J})}Se(a){const b=a.tag,g=a.message,t=a.mode;(a=this.sb(a.id))&&a.ka(t,JSON.stringify({c:"m",t:b,m:g}))}yd(a,b){z(this,"peer-close",{id:a.j,alias:a.J,reason:b||"unknown"})}Z(a,b){console.error(`[Multiplayer] Peer '${a.J}' (${a.j}) error: `,b)}tg(a,b){a=b.f||a.j;z(this,"peer-message",{tag:b.t,fromId:a,fromAlias:this.qe(a),content:b.m})}mg(a,b,g){z(this,"instance-destroyed",{roId:a.lb,nid:b,timestamp:g})}Re(a){if(this.g()){var b=a.reason;(a=this.sb(a.id))&&a.C(b,!0)}}tf(){this.ya.$c++}rf(a){this.ya.Xb+=
a}sf(){this.ya.Yc++}qf(a){this.ya.Wb+=a}cf(a){this.U=a}gf(a){this.hb=a}We(a){const b=a.data,g=a.precision,t=a.bandwidth;for(const w of a.objectClasses)a=new self.me(this,w.roId,w.sid,t),1===b?(a.ia(1,g,"x"),a.ia(1,g,"y")):2===b?a.ia(2,g,"a"):3===b&&(a.ia(1,g,"x"),a.ia(1,g,"y"),a.ia(2,g,"a"))}ie(a){alert(a.message)}Ve(a){const b=a.precision,g=a.interp,t=a.cvt;for(const w of a.syncData)this.kb.get(w.roId).ia(g,b,"iv",w.varIndex,t)}Pe(a){var b=a.peerId;const g=a.instUid;a=this.kb.get(a.roId);b=this.ga.get(b);
a&&b&&this.g()&&a.Xe(g,b.D)}Te(a){for(const [b,g]of Object.entries(a))if(a=this.kb.get(parseInt(b,10)))for(const t of g)a.kc(t)}Ue(a){const b=a.nid;(a=this.kb.get(a.roId))&&a.kc(b)}})};
